config/routes.rb
TodoList::Application.routes.draw do
  match '/new_session' => "authentication#new", :as => :new_session
  match '/login' => "authentication#login", :as => :login
  match '/logout' => "authentication#logout", :as => :logout

  resources :users, :only => [:new, :create, :update]
  match '/account' => "users#edit", :as => :account

  resources :tasks do
    member do
      get :done
    end
  end

  root :to => 'tasks#index'

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  set_table_name "ckeditor_assets"
  
  belongs_to :user
  belongs_to :assetable, :polymorphic => true
  
  scope :masters, where("parent_id IS NULL")
  
  def url(*args)
    public_filename(*args)
  end
  
  def format_created_at
    I18n.l(self.created_at, :format=>"%d.%m.%Y %H:%M")
  end
  
  def to_xml(options = {})
    xml = options[:builder] ||= Builder::XmlMarkup.new(:indent => options[:indent])

    xml.tag!(self.read_attribute(:type).to_s.downcase) do
      xml.filename{ xml.cdata!(self.filename) }
      xml.size self.size
      xml.path{ xml.cdata!(self.public_filename) }
      
      xml.thumbnails do
        self.thumbnails.each do |t|
          xml.tag!(t.thumbnail, self.public_filename(t.thumbnail))
        end
      end unless self.thumbnails.empty?
    end
  end
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
#  has_attachment :storage => :file_system, :path_prefix => 'public/assets/attachments',
#                 :max_size => 10.megabytes
  
#validates_as_attachment
  
  # Map file extensions to mime types.
  # Thanks to bug in Flash 8 the content type is always set to application/octet-stream.
  # From: http://blog.airbladesoftware.com/2007/8/8/uploading-files-with-swfupload
  def swf_uploaded_data=(data)
    data.content_type = MIME::Types.type_for(data.original_filename)
    self.uploaded_data = data
  end
  
  def full_filename(thumbnail = nil)
    file_system_path = self.attachment_options[:path_prefix]
    Rails.root.join(file_system_path, file_name_for(self.id))
  end
  
  def file_name_for(asset = nil)
    extension = filename.scan(/\.\w+$/)
    return "#{asset}_#{filename}"
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
##has_attachment :content_type => :image, 
##               :storage => :file_system, :path_prefix => 'public/assets/pictures',
##               :max_size => 2.megabytes,
##               :size => 0.kilobytes..2000.kilobytes,
##               :processor => 'Rmagick',
##               :thumbnails => { :content => '575>', :thumb => '100x100!' }
##               
##validates_as_attachment
  
  def url_content
	  public_filename(:content)
	end
	
	def url_thumb
	  public_filename(:thumb)
	end
	
	def to_json(options = {})
	  options[:methods] ||= []
	  options[:methods] << :url_content
	  options[:methods] << :url_thumb
	  super options
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user

  scope :todo, where(:done => false)
  scope :done, where(:done => true)
  validates_presence_of :title

  def done!
    self.update_attributes :done => true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks

  attr_accessor :password_confirmation

  validates :login, :presence => true, :uniqueness => true

  with_options :if => :password_required? do |v|
    v.validates_presence_of :password
    v.validates_confirmation_of :password
    v.validates_length_of :password, :within => 6..20, :allow_blank => true
  end

  protected
  def password_required?
    !persisted? || !password.blank? || !password_confirmation.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  protected
  def authenticate(user)
    session[:user_id] = user.id
  end
  def require_authentication
    unless current_user
      flash[:error] = 'You must to be logged in'
      redirect_to new_session_url
    end
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def new
  end

  def login
    user = User.find_by_login(params[:username])
    if user && user.password == params[:password]
      authenticate(user)
      redirect_to tasks_url, :notice => 'You are in dude!'
    else
      flash[:error] = "Username and password don't match"
      redirect_to :action => :new
    end
  end

  def logout
    session.delete(:user_id)
    redirect_to :action => :new
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :require_authentication
  # GET /tasks
  # GET /tasks.xml
  def index
    @todo_tasks = current_user.tasks.todo
    @done_tasks = current_user.tasks.done

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.xml
  def show
    @task = current_user.tasks.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.xml
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = current_user.tasks.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.xml
  def create
    @task = current_user.tasks.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to(tasks_url, :notice => 'Task was successfully created.') }
        format.xml  { render :xml => @task, :status => :created, :location => @task }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.xml
  def update
    @task = current_user.tasks.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to(@task, :notice => 'Task was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @task.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.xml
  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to(tasks_url) }
      format.xml  { head :ok }
    end
  end

  def done
    @task = current_user.tasks.find(params[:id])
    @task.done!
    redirect_to tasks_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_authentication, :only => [:edit, :update, :destroy]

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        authenticate(@user)
        format.html { redirect_to(tasks_url, :notice => 'User was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # GET /users/1/edit
  def edit
    @user = current_user
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = current_user

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(tasks_url, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = current_user
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(tasks_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authentication/new.html.erb
<h1>Login</h1>

<p id='errors'><%= flash[:error] %></p>

<%= form_tag login_url do %>
  <div class='field'>
    <%= label_tag :username %><br/>
    <%= text_field_tag :username %>
  </div>
  <div class='field'>
    <%= label_tag :password %><br/>
    <%= password_field_tag :password %>
  </div>
  <div class='actions'>
    <%= submit_tag 'Login' %> | <%= link_to 'Sign up', new_user_url %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag :ckeditor %>

  <%= csrf_meta_tag %>
</head>
<body>
<div id="container">
<% if current_user %>
  <%= link_to 'Edit account', account_url %> |
  <%= link_to 'Logout', logout_url %>
<% end %>
<hr/>
<%- flash.each do |name, msg| -%>
<%= content_tag :div, msg, :id => "flash_#{name}" %>
<%- end -%>
<%= yield %>
</div>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>

  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= ckeditor_textarea( "task","description", :width => '100%', :height => '200px') %>
    <%#= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1><%= current_user.login %>'s Tasks</h1>

<h2>To-do</h2>
<% @todo_tasks.each do |task| %>
<div class=" task-box shadow">
   <b> <%= task.title %></b>
   <div style="float:right"><%= task.created_at.strftime("%d %B %Y")%></div>
   <br/>
    <%= link_to 'Show', task %>
    <%= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete %>
    <%= link_to 'Done!', done_task_url(task) %>
</div>
<% end %>

<h2>Done</h2>
<% @done_tasks.each do |task| %>
<div class=" task-box shadow">
   <b> <%= task.title %></b><br/>
    <%= link_to 'Show', task %>
    <%= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete %>
</div>
<% end %>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p>
  <b>Title:</b>
  <%= @task.title %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, :value => nil %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', new_session_path %>